### ISSUE TITLE
运行不了提示缺少函数

### ISSUE THREAD

**Issue by shihangbin** [ay86/multer-aliyun-oss#16]
运行不了提示缺少函数,博主能给个完善代码实例嘛
![image](https://github.com/ay86/multer-aliyun-oss/assets/67466410/8283eaa2-1a22-4c4a-a1ef-337add89d3c8)
![image](https://github.com/ay86/multer-aliyun-oss/assets/67466410/75957b02-91f2-42db-a056-cdd7f7168c87)

**Comment by ay86** [comment]
你好，看了你提供的截图。似乎你的问题是出现在 multer 上面的。并未提供你的实例代码部分，所以也不清楚你的问题所在。
